---
# OpenWrt Mesh Network Inventory
#
# Initial access (before configuration):
#   All nodes start at 192.168.1.1
#   You must configure ONE node at a time initially
#   Set ansible_host to 192.168.1.1 and run playbook
#   After first node configured, update ansible_host to 10.11.12.X
#
# After configuration:
#   Nodes will be at 10.11.12.1, 10.11.12.2, 10.11.12.3

all:
  children:
    mesh_nodes:
      children:
        gateway_primary:
          hosts:
            node1:
              ansible_host: 10.11.12.1
              node_ip: 10.11.12.1
              node_id: 1
              dhcp_server: true
              mesh_ports:
                lan3: node2
                lan4: node3

        gateway_secondary:
          hosts:
            node2:
              ansible_host: 10.11.12.2
              node_ip: 10.11.12.2
              node_id: 2
              dhcp_server: false
              mesh_ports:
                lan3: node1
                lan4: node3

            node3:
              ansible_host: 10.11.12.3
              node_ip: 10.11.12.3
              node_id: 3
              dhcp_server: false
              mesh_ports:
                lan3: node2
                lan4: node1

  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    # Set this to your SSH key or use password authentication initially
    # ansible_ssh_pass: your_password
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
