---
# OpenWrt Mesh Network Inventory - PRODUCTION
#
# Use this inventory for managing CONFIGURED mesh nodes
#
# For initial setup of fresh nodes, use inventory/hosts-initial.yml instead
#
# This inventory assumes all nodes have been configured and are at:
#   - Node 1: 10.11.12.1 (Primary Gateway - has WAN)
#   - Node 2: 10.11.12.2 (Mesh Node - no WAN)
#   - Node 3: 10.11.12.3 (Secondary Gateway - has WAN)
#
# Gateway Mode:
#   - has_wan: true  -> gw_mode 'server' (advertises internet gateway)
#   - has_wan: false -> gw_mode 'client' (uses other nodes for internet)

all:
  children:
    mesh_nodes:
      children:
        gateway_primary:
          hosts:
            node1:
              ansible_host: 10.11.12.1
              node_ip: 10.11.12.1
              node_id: 1
              has_wan: true
              mesh_ports:
                lan3: node2
                lan4: node3

        gateway_secondary:
          hosts:
            node2:
              ansible_host: 10.11.12.2
              node_ip: 10.11.12.2
              node_id: 2
              has_wan: false
              mesh_ports:
                lan3: node1
                lan4: node3

            node3:
              ansible_host: 10.11.12.3
              node_ip: 10.11.12.3
              node_id: 3
              has_wan: true
              mesh_ports:
                lan3: node2
                lan4: node1

  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

    # Production nodes use openssh (not dropbear) with SSH KEY authentication
    # SSH key is automatically deployed during initial setup (deploy-initial-nodeX)
    # Key location is sourced from SSH_KEY_PATH environment variable
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/openwrt_mesh_rsa', true) }}"

    # OpenSSH-specific options
    # - StrictHostKeyChecking=no: Accept host keys (mesh network is controlled)
    # - UserKnownHostsFile=/dev/null: Don't track host keys (IPs may change)
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    # Note: Root password is still set (for console access) but not used for SSH
